/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TrustSafetyRouteImport } from './routes/trust-safety'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BecomeListerRouteImport } from './routes/become-lister'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as ProfileListingsRouteImport } from './routes/profile.listings'
import { Route as ProfileBookingsRouteImport } from './routes/profile.bookings'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as JournalIdRouteImport } from './routes/journal.$id'
import { Route as CategoriesIdRouteImport } from './routes/categories.$id'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedDashboardTabRouteImport } from './routes/_authenticated/dashboard.$tab'
import { Route as AuthenticatedAccountReviewsRouteImport } from './routes/_authenticated/account.reviews'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account.profile'
import { Route as AuthenticatedAccountPaymentsRouteImport } from './routes/_authenticated/account.payments'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated/account.notifications'
import { Route as AuthenticatedAccountMessagesRouteImport } from './routes/_authenticated/account.messages'
import { Route as AuthenticatedAccountListingsRouteImport } from './routes/_authenticated/account.listings'
import { Route as AuthenticatedAccountCouponsRouteImport } from './routes/_authenticated/account.coupons'
import { Route as AuthenticatedAccountBookingsRouteImport } from './routes/_authenticated/account.bookings'
import { Route as AuthenticatedAdminAdminDashboardRouteImport } from './routes/_authenticated/_admin/admin.dashboard'
import { Route as AuthenticatedAdminAdminDashboardIndexRouteImport } from './routes/_authenticated/_admin/admin.dashboard.index'
import { Route as AuthenticatedAdminAdminDashboardTabRouteImport } from './routes/_authenticated/_admin/admin.dashboard.$tab'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustSafetyRoute = TrustSafetyRouteImport.update({
  id: '/trust-safety',
  path: '/trust-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeListerRoute = BecomeListerRouteImport.update({
  id: '/become-lister',
  path: '/become-lister',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileListingsRoute = ProfileListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileBookingsRoute = ProfileBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const JournalIdRoute = JournalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JournalRoute,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CategoriesRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedDashboardTabRoute =
  AuthenticatedDashboardTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAccountReviewsRoute =
  AuthenticatedAccountReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountPaymentsRoute =
  AuthenticatedAccountPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountMessagesRoute =
  AuthenticatedAccountMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountListingsRoute =
  AuthenticatedAccountListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountCouponsRoute =
  AuthenticatedAccountCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountBookingsRoute =
  AuthenticatedAccountBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminAdminDashboardRoute =
  AuthenticatedAdminAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDashboardIndexRoute =
  AuthenticatedAdminAdminDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminDashboardRoute,
  } as any)
const AuthenticatedAdminAdminDashboardTabRoute =
  AuthenticatedAdminAdminDashboardTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedAdminAdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-lister': typeof BecomeListerRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/journal/$id': typeof JournalIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/profile/bookings': typeof ProfileBookingsRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/users/$id': typeof UsersIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/account/coupons': typeof AuthenticatedAccountCouponsRoute
  '/account/listings': typeof AuthenticatedAccountListingsRoute
  '/account/messages': typeof AuthenticatedAccountMessagesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/payments': typeof AuthenticatedAccountPaymentsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/reviews': typeof AuthenticatedAccountReviewsRoute
  '/dashboard/$tab': typeof AuthenticatedDashboardTabRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRouteWithChildren
  '/admin/dashboard/$tab': typeof AuthenticatedAdminAdminDashboardTabRoute
  '/admin/dashboard/': typeof AuthenticatedAdminAdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-lister': typeof BecomeListerRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/journal/$id': typeof JournalIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/profile/bookings': typeof ProfileBookingsRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/users/$id': typeof UsersIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/journal': typeof JournalIndexRoute
  '/products': typeof ProductsIndexRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/account/coupons': typeof AuthenticatedAccountCouponsRoute
  '/account/listings': typeof AuthenticatedAccountListingsRoute
  '/account/messages': typeof AuthenticatedAccountMessagesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/payments': typeof AuthenticatedAccountPaymentsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/reviews': typeof AuthenticatedAccountReviewsRoute
  '/dashboard/$tab': typeof AuthenticatedDashboardTabRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/dashboard/$tab': typeof AuthenticatedAdminAdminDashboardTabRoute
  '/admin/dashboard': typeof AuthenticatedAdminAdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/become-lister': typeof BecomeListerRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/journal/$id': typeof JournalIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/profile/bookings': typeof ProfileBookingsRoute
  '/profile/listings': typeof ProfileListingsRoute
  '/users/$id': typeof UsersIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/_authenticated/account/coupons': typeof AuthenticatedAccountCouponsRoute
  '/_authenticated/account/listings': typeof AuthenticatedAccountListingsRoute
  '/_authenticated/account/messages': typeof AuthenticatedAccountMessagesRoute
  '/_authenticated/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/account/payments': typeof AuthenticatedAccountPaymentsRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/reviews': typeof AuthenticatedAccountReviewsRoute
  '/_authenticated/dashboard/$tab': typeof AuthenticatedDashboardTabRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/_admin/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRouteWithChildren
  '/_authenticated/_admin/admin/dashboard/$tab': typeof AuthenticatedAdminAdminDashboardTabRoute
  '/_authenticated/_admin/admin/dashboard/': typeof AuthenticatedAdminAdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-lister'
    | '/categories'
    | '/contact'
    | '/download'
    | '/help'
    | '/how-it-works'
    | '/journal'
    | '/login'
    | '/oauth-callback'
    | '/pricing'
    | '/products'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/trust-safety'
    | '/verify-email'
    | '/account'
    | '/dashboard'
    | '/wishlist'
    | '/categories/$id'
    | '/journal/$id'
    | '/products/$id'
    | '/profile/bookings'
    | '/profile/listings'
    | '/users/$id'
    | '/categories/'
    | '/journal/'
    | '/products/'
    | '/account/bookings'
    | '/account/coupons'
    | '/account/listings'
    | '/account/messages'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/account/profile'
    | '/account/reviews'
    | '/dashboard/$tab'
    | '/account/'
    | '/dashboard/'
    | '/admin/dashboard'
    | '/admin/dashboard/$tab'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-lister'
    | '/contact'
    | '/download'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/oauth-callback'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/trust-safety'
    | '/verify-email'
    | '/wishlist'
    | '/categories/$id'
    | '/journal/$id'
    | '/products/$id'
    | '/profile/bookings'
    | '/profile/listings'
    | '/users/$id'
    | '/categories'
    | '/journal'
    | '/products'
    | '/account/bookings'
    | '/account/coupons'
    | '/account/listings'
    | '/account/messages'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/account/profile'
    | '/account/reviews'
    | '/dashboard/$tab'
    | '/account'
    | '/dashboard'
    | '/admin/dashboard/$tab'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/become-lister'
    | '/categories'
    | '/contact'
    | '/download'
    | '/help'
    | '/how-it-works'
    | '/journal'
    | '/login'
    | '/oauth-callback'
    | '/pricing'
    | '/products'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/trust-safety'
    | '/verify-email'
    | '/_authenticated/_admin'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/wishlist'
    | '/categories/$id'
    | '/journal/$id'
    | '/products/$id'
    | '/profile/bookings'
    | '/profile/listings'
    | '/users/$id'
    | '/categories/'
    | '/journal/'
    | '/products/'
    | '/_authenticated/account/bookings'
    | '/_authenticated/account/coupons'
    | '/_authenticated/account/listings'
    | '/_authenticated/account/messages'
    | '/_authenticated/account/notifications'
    | '/_authenticated/account/orders'
    | '/_authenticated/account/payments'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/reviews'
    | '/_authenticated/dashboard/$tab'
    | '/_authenticated/account/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/_admin/admin/dashboard'
    | '/_authenticated/_admin/admin/dashboard/$tab'
    | '/_authenticated/_admin/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BecomeListerRoute: typeof BecomeListerRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JournalRoute: typeof JournalRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrustSafetyRoute: typeof TrustSafetyRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  UsersIdRoute: typeof UsersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-safety': {
      id: '/trust-safety'
      path: '/trust-safety'
      fullPath: '/trust-safety'
      preLoaderRoute: typeof TrustSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-lister': {
      id: '/become-lister'
      path: '/become-lister'
      fullPath: '/become-lister'
      preLoaderRoute: typeof BecomeListerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/listings': {
      id: '/profile/listings'
      path: '/listings'
      fullPath: '/profile/listings'
      preLoaderRoute: typeof ProfileListingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/bookings': {
      id: '/profile/bookings'
      path: '/bookings'
      fullPath: '/profile/bookings'
      preLoaderRoute: typeof ProfileBookingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/journal/$id': {
      id: '/journal/$id'
      path: '/$id'
      fullPath: '/journal/$id'
      preLoaderRoute: typeof JournalIdRouteImport
      parentRoute: typeof JournalRoute
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/dashboard/$tab': {
      id: '/_authenticated/dashboard/$tab'
      path: '/$tab'
      fullPath: '/dashboard/$tab'
      preLoaderRoute: typeof AuthenticatedDashboardTabRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/account/reviews': {
      id: '/_authenticated/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AuthenticatedAccountReviewsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/payments': {
      id: '/_authenticated/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AuthenticatedAccountPaymentsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/notifications': {
      id: '/_authenticated/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/messages': {
      id: '/_authenticated/account/messages'
      path: '/messages'
      fullPath: '/account/messages'
      preLoaderRoute: typeof AuthenticatedAccountMessagesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/listings': {
      id: '/_authenticated/account/listings'
      path: '/listings'
      fullPath: '/account/listings'
      preLoaderRoute: typeof AuthenticatedAccountListingsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/coupons': {
      id: '/_authenticated/account/coupons'
      path: '/coupons'
      fullPath: '/account/coupons'
      preLoaderRoute: typeof AuthenticatedAccountCouponsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/bookings': {
      id: '/_authenticated/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AuthenticatedAccountBookingsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_admin/admin/dashboard': {
      id: '/_authenticated/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/dashboard/': {
      id: '/_authenticated/_admin/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AuthenticatedAdminAdminDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminDashboardRoute
    }
    '/_authenticated/_admin/admin/dashboard/$tab': {
      id: '/_authenticated/_admin/admin/dashboard/$tab'
      path: '/$tab'
      fullPath: '/admin/dashboard/$tab'
      preLoaderRoute: typeof AuthenticatedAdminAdminDashboardTabRouteImport
      parentRoute: typeof AuthenticatedAdminAdminDashboardRoute
    }
  }
}

interface AuthenticatedAdminAdminDashboardRouteChildren {
  AuthenticatedAdminAdminDashboardTabRoute: typeof AuthenticatedAdminAdminDashboardTabRoute
  AuthenticatedAdminAdminDashboardIndexRoute: typeof AuthenticatedAdminAdminDashboardIndexRoute
}

const AuthenticatedAdminAdminDashboardRouteChildren: AuthenticatedAdminAdminDashboardRouteChildren =
  {
    AuthenticatedAdminAdminDashboardTabRoute:
      AuthenticatedAdminAdminDashboardTabRoute,
    AuthenticatedAdminAdminDashboardIndexRoute:
      AuthenticatedAdminAdminDashboardIndexRoute,
  }

const AuthenticatedAdminAdminDashboardRouteWithChildren =
  AuthenticatedAdminAdminDashboardRoute._addFileChildren(
    AuthenticatedAdminAdminDashboardRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminDashboardRoute: typeof AuthenticatedAdminAdminDashboardRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminDashboardRoute:
    AuthenticatedAdminAdminDashboardRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountBookingsRoute: typeof AuthenticatedAccountBookingsRoute
  AuthenticatedAccountCouponsRoute: typeof AuthenticatedAccountCouponsRoute
  AuthenticatedAccountListingsRoute: typeof AuthenticatedAccountListingsRoute
  AuthenticatedAccountMessagesRoute: typeof AuthenticatedAccountMessagesRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountPaymentsRoute: typeof AuthenticatedAccountPaymentsRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountReviewsRoute: typeof AuthenticatedAccountReviewsRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountBookingsRoute: AuthenticatedAccountBookingsRoute,
  AuthenticatedAccountCouponsRoute: AuthenticatedAccountCouponsRoute,
  AuthenticatedAccountListingsRoute: AuthenticatedAccountListingsRoute,
  AuthenticatedAccountMessagesRoute: AuthenticatedAccountMessagesRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
  AuthenticatedAccountPaymentsRoute: AuthenticatedAccountPaymentsRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountReviewsRoute: AuthenticatedAccountReviewsRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardTabRoute: typeof AuthenticatedDashboardTabRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardTabRoute: AuthenticatedDashboardTabRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CategoriesRouteChildren {
  CategoriesIdRoute: typeof CategoriesIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesIdRoute: CategoriesIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface JournalRouteChildren {
  JournalIdRoute: typeof JournalIdRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalIdRoute: JournalIdRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileBookingsRoute: typeof ProfileBookingsRoute
  ProfileListingsRoute: typeof ProfileListingsRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileBookingsRoute: ProfileBookingsRoute,
  ProfileListingsRoute: ProfileListingsRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BecomeListerRoute: BecomeListerRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrustSafetyRoute: TrustSafetyRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  UsersIdRoute: UsersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
