import { useState } from 'react'
import { Button } from '#/components/ui/button'
import { Input } from '#/components/ui/input'
import { Label } from '#/components/ui/label'
import {
  Fingerprint,
  ShieldCheck,
  ShieldAlert,
  Copy,
  Check,
  CheckCircle2,
  Leaf,
} from 'lucide-react'
import { Loader } from '#/components/ui/loader'
import { toast } from 'sonner'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '#/components/ui/dialog'

interface TwoFactorDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  twoFactorEnabled: boolean
  setTwoFactorEnabled: (enabled: boolean) => void
  userEmail?: string
}

export function TwoFactorDialog({
  open,
  onOpenChange,
  twoFactorEnabled,
  setTwoFactorEnabled,
  userEmail,
}: TwoFactorDialogProps) {
  const [twoFactorStep, setTwoFactorStep] = useState<'intro' | 'setup' | 'success'>('intro')
  const [twoFactorCode, setTwoFactorCode] = useState('')
  const [twoFactorError, setTwoFactorError] = useState<string | null>(null)
  const [twoFactorBackupCodes, setTwoFactorBackupCodes] = useState<string[]>([])
  const [isCopyingKey, setIsCopyingKey] = useState(false)
  const [isVerifying2fa, setIsVerifying2fa] = useState(false)

  const email = userEmail || ''
  const secretKey = 'VASTUAUTHKEYRENT'
  const displayKey = 'VASTU-AUTH-KEY-RENT'
  const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=160x160&data=${encodeURIComponent(
    `otpauth://totp/Vastu:${email}?secret=${secretKey}&issuer=Vastu`
  )}`

  const handleEnable2fa = () => {
    setTwoFactorStep('setup')
    setTwoFactorCode('')
    setTwoFactorError(null)
  }

  const handleVerify2fa = () => {
    if (twoFactorCode.length !== 6 || !/^\d+$/.test(twoFactorCode)) {
      setTwoFactorError('Please enter a valid 6-digit number.')
      return
    }

    setIsVerifying2fa(true)
    setTimeout(() => {
      setIsVerifying2fa(false)
      const recovery = Array.from(
        { length: 8 },
        () =>
          Math.random().toString(36).substring(2, 7).toUpperCase() +
          '-' +
          Math.random().toString(36).substring(2, 7).toUpperCase()
      )
      setTwoFactorBackupCodes(recovery)
      setTwoFactorEnabled(true)
      setTwoFactorStep('success')
      toast.success('Two-factor authentication enabled successfully!')
    }, 1000)
  }

  const handleDisable2fa = () => {
    if (confirm('Are you sure you want to disable 2FA? This will make your account less secure.')) {
      setTwoFactorEnabled(false)
      setTwoFactorStep('intro')
      toast.success('Two-factor authentication disabled.')
    }
  }

  return (
    <Dialog open={open} onOpenChange={(openVal) => {
      onOpenChange(openVal)
      if (!openVal) {
        setTwoFactorStep('intro')
      }
    }}>
      <DialogContent className="sm:max-w-[420px] rounded-[32px] border-none bg-white/90 backdrop-blur-md p-6 shadow-2xl animate-scale-in">
        <DialogHeader className="text-left">
          <DialogTitle className="text-xl font-black text-gray-900 font-display flex items-center gap-2">
            <Fingerprint className="h-5 w-5 text-primary" />
            Two-Factor Authentication
          </DialogTitle>
          <DialogDescription className="text-xs text-gray-500 font-medium">
            Secure your Vastu profile with an authenticator app (Google Authenticator, Duo, or 1Password).
          </DialogDescription>
        </DialogHeader>

        {twoFactorStep === 'intro' && (
          <div className="space-y-5 py-2 animate-fade-in">
            <div className="flex gap-4 items-start bg-slate-50/50 p-4 rounded-2xl border border-slate-100 text-left">
              <div className="h-10 w-10 bg-primary/10 rounded-full flex items-center justify-center text-primary shrink-0">
                <ShieldCheck size={20} />
              </div>
              <div>
                <h4 className="text-xs font-bold text-gray-900">How 2FA protects you</h4>
                <p className="text-[11px] text-gray-400 font-medium mt-0.5 leading-normal">
                  When signing in, you'll be asked to provide a 6-digit verification code generated by your app, protecting your listings from unauthorized changes.
                </p>
              </div>
            </div>

            <div className="flex gap-3 pt-2">
              {twoFactorEnabled ? (
                <Button
                  onClick={handleDisable2fa}
                  className="w-full rounded-xl h-11 font-bold bg-red-50 hover:bg-red-100 text-red-600 border border-red-200 cursor-pointer shadow-none"
                >
                  Disable 2FA
                </Button>
              ) : (
                <Button
                  onClick={handleEnable2fa}
                  className="w-full rounded-xl h-11 font-bold bg-[#2d5222] hover:bg-[#203a18] text-white flex items-center justify-center gap-1.5 shadow-lg shadow-[#2d5222]/10 cursor-pointer border-none"
                >
                  Set Up 2FA App
                </Button>
              )}
            </div>
          </div>
        )}

        {twoFactorStep === 'setup' && (
          <div className="space-y-4 py-1 animate-fade-in">
            <div className="flex flex-col items-center justify-center p-4 bg-[#F4F8F1] rounded-2xl border border-[#e6efe1] relative">
              {/* Premium scannable QR Code */}
              <div className="h-40 w-40 bg-white p-2 rounded-xl shadow-sm border border-gray-100 flex items-center justify-center relative overflow-hidden group">
                <img
                  src={qrCodeUrl}
                  alt="Vastu 2FA QR Code"
                  className="w-full h-full object-contain"
                />
                {/* Embedded Leaf Icon in center of scannable QR */}
                <div className="absolute inset-0 m-auto h-8 w-8 rounded-lg bg-[#2d5222] border-2 border-white flex items-center justify-center shadow-md pointer-events-none">
                  <Leaf size={14} className="text-white fill-white" />
                </div>
              </div>
              <span className="text-[9px] text-[#2d5222] font-extrabold uppercase tracking-widest mt-2">Scan QR Code</span>
            </div>

            {/* Secret Key Display */}
            <div className="space-y-1 text-left">
              <Label className="text-[10px] font-bold text-gray-400">Can't scan? Enter key manually</Label>
              <div className="flex gap-2">
                <div className="flex-1 bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-xs font-mono font-bold text-gray-600 flex items-center select-all">
                  {displayKey}
                </div>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    navigator.clipboard.writeText(displayKey)
                    setIsCopyingKey(true)
                    toast.success('Secret key copied!')
                    setTimeout(() => setIsCopyingKey(false), 2000)
                  }}
                  className="h-10 w-10 p-0 rounded-xl border-gray-200 text-gray-600 hover:bg-gray-50 flex items-center justify-center cursor-pointer shadow-none shrink-0"
                >
                  {isCopyingKey ? <Check size={16} className="text-[#2d5222]" /> : <Copy size={16} />}
                </Button>
              </div>
            </div>

            {/* Code Verification */}
            <div className="space-y-1.5 text-left">
              <Label className="text-xs font-bold text-gray-400">Enter Verification Code</Label>
              <Input
                type="text"
                maxLength={6}
                placeholder="Enter 6-digit code"
                value={twoFactorCode}
                onChange={(e) => setTwoFactorCode(e.target.value.replace(/\D/g, ''))}
                className="h-11 rounded-xl border-gray-200 bg-gray-50/30 text-center font-mono font-bold tracking-widest text-lg focus:ring-primary/20"
              />
              {twoFactorError && (
                <p className="text-[10px] text-red-500 font-bold mt-1 animate-fade-in flex items-center gap-1">
                  <ShieldAlert size={10} />
                  {twoFactorError}
                </p>
              )}
            </div>

            <div className="flex gap-3 pt-2">
              <Button
                type="button"
                variant="outline"
                onClick={() => setTwoFactorStep('intro')}
                className="flex-1 rounded-xl h-11 font-bold border-gray-200 text-gray-700 hover:bg-gray-50 cursor-pointer shadow-none"
              >
                Back
              </Button>
              <Button
                type="button"
                disabled={isVerifying2fa}
                onClick={handleVerify2fa}
                className="flex-1 rounded-xl h-11 font-bold bg-[#2d5222] hover:bg-[#203a18] text-white flex items-center justify-center gap-1.5 shadow-lg shadow-[#2d5222]/10 cursor-pointer border-none"
              >
                {isVerifying2fa ? <Loader variant="white" size={14} /> : null}
                Verify & Activate
              </Button>
            </div>
          </div>
        )}

        {twoFactorStep === 'success' && (
          <div className="space-y-5 py-2 animate-fade-in text-center">
            <div className="h-16 w-16 bg-[#F4F8F1] border border-[#e6efe1] rounded-full flex items-center justify-center text-[#2d5222] mx-auto animate-bounce">
              <CheckCircle2 size={36} className="stroke-[2.5]" />
            </div>

            <div>
              <h3 className="text-base font-extrabold text-gray-900 font-display">2FA Enabled Successfully!</h3>
              <p className="text-[11px] text-gray-400 font-medium mt-1">
                Save these emergency backup/recovery codes. Each code can be used once if you lose your phone or app.
              </p>
            </div>

            {/* Backup Codes Grid */}
            <div className="grid grid-cols-2 gap-2 bg-slate-50 border border-slate-100 p-4 rounded-2xl font-mono text-[10px] font-bold text-gray-600 text-left shadow-inner">
              {twoFactorBackupCodes.map((code, i) => (
                <div key={i} className="flex gap-1.5 items-center">
                  <span className="text-gray-300 font-semibold select-none">{i + 1}.</span>
                  <span className="select-all">{code}</span>
                </div>
              ))}
            </div>

            <div className="flex gap-3 pt-2">
              <Button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(twoFactorBackupCodes.join('\n'))
                  toast.success('Codes copied!')
                }}
                className="flex-1 rounded-xl h-11 font-bold bg-slate-150 hover:bg-slate-200 text-gray-800 border-none cursor-pointer shadow-none"
              >
                Copy Codes
              </Button>
              <Button
                type="button"
                onClick={() => onOpenChange(false)}
                className="flex-1 rounded-xl h-11 font-bold bg-[#2d5222] hover:bg-[#203a18] text-white cursor-pointer shadow-lg shadow-[#2d5222]/10 border-none"
              >
                Done
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}
